deployment:
 tasks:
 - export DEPLOYPATH=/home/earlygra/public_html/
 - /bin/cp *.html $DEPLOYPATH
 - /bin/cp *.css $DEPLOYPATH
 - /bin/cp CNAME $DEPLOYPATH
 - /bin/cp favicon.ico $DEPLOYPATH
 - /bin/cp -r img $DEPLOYPATH
